BEGIN;

-- Migrating events (18 rows)
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Hack4Good', 'Devfolio Community', 'Fri May 08 2026', 'Sat May 09 2026', 'Hack4Good v0 is a 24-hour sprint focused on building intelligent, agentic software systems that go beyond traditional task-based coding. Instead of writing more boilerplate, participants will design AI agents that can plan workflows, navigate the web, and execute tasks autonomously. The hackathon is open to student developers, tinkerers, and builders who enjoy working with systems, architectures, and ambitious ideas, whether it’s a weekend experiment or a project meant to ship. With a strong emphasis on hands-on building, collaboration, and learning at the bleeding edge of AI, Hack4Good v0 is completely free and open to anyone willing to show up and build!!!!', 'https://devfolio.co', 'Lucknow', 'Hackathon', 'Devfolio', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Algo Heist', 'Indira Gandhi Delhi Technical University for Women (IGDTUW), Delhi', 'Tue Feb 17 2026', 'Sun Mar 15 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/algo-heist-innerve-2026-igdtuw-delhi-1643572', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('IoT Nexus 2026', 'Shri Mata Vaishno Devi University (SMVDU), Katra', 'Thu Feb 26 2026', 'Sun Mar 08 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/iot-nexus-2026-ekatva-shri-mata-vaishno-devi-university-smvdu-katra-1649137', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Technothon- Aayam 2026', 'National Institute of Technology (NIT), Agartala', 'Wed Feb 25 2026', 'Sun Mar 08 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/technothon-aayam-2026-national-institute-of-technology-nit-agartala-1648458', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Atria Summer of Code', 'Atria Institute of Technology (AIT), Bengaluru, Karnataka', 'Thu Feb 26 2026', 'Wed May 13 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/atria-summer-of-code-atria-institute-of-technology-ait-bengaluru-karnataka-1649077', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Roborace', 'Delhi Technological University (DTU), New Delhi', 'Thu Feb 26 2026', 'Thu Mar 12 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/roborace-invictus-2026-dtu-new-delhi-1648931', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Secure AI Software and Systems Hackathon', 'BITS Pilani, K K Birla Goa Campus', 'Thu Feb 26 2026', 'Sun Mar 29 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/secure-ai-software-and-systems-hackathon-bits-pilani-k-k-birla-goa-campus-1648624', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Hardware Hackathon 3.0', 'Prathyusha Engineering College (PEC),Thiruvallur', 'Thu Feb 26 2026', 'Thu Mar 12 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/hardware-hackathon-30-prathyusha-engineering-college-pecthiruvallur-1648869', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('SJCE CSE Hackathon 2K26', 'St. Joseph College of Engineering', 'Mon Feb 23 2026', 'Mon Mar 23 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/sjce-cse-hackathon-2k26-st-joseph-college-of-engineering-1637340', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Code War', 'Tezpur University (TEZU), Tezpur', 'Mon Feb 23 2026', 'Mon Mar 02 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/code-war-inscignis-2026-tezpur-university-tezu-tezpur-1646978', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Hack and Shield', 'IIITDM Kancheepuram', 'Tue Feb 24 2026', 'Mon Mar 30 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/hack-and-shield-savara-iiitdm-kancheepuram-1640035', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('AlgoXchange', 'IIITDM Kancheepuram', 'Wed Feb 25 2026', 'Sun Mar 29 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/algoxchange-savara-iiitdm-kancheepuram-1648423', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('AI Arena : Gotham Edition', 'KIET Group of Institutions', 'Tue Feb 24 2026', 'Fri Mar 20 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/ai-arena-gotham-edition-kiet-group-of-institutions-1640378', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Livron2K26-"From Tradition to Innovation: Reimagining Indian Foods for Modern Nutrition"', 'Sree Sastha Institute of Engineering and Technology (SSIET), Tamil Nadu', 'Thu Feb 26 2026', 'Thu Mar 12 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/livron2k26-from-tradition-to-innovation-reimagining-indian-foods-for-modern-nutrition-livron2k26-sree-sastha--1648686', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('The MarvelX', 'R. C. Patel Institute of Technology, Shirpur, Maharashtra', 'Wed Feb 25 2026', 'Sat Mar 07 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/the-marvelx-converges26-r-c-patel-institute-of-technology-shirpur-maharashtra-1648009', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Train Z', 'R. C. Patel Institute of Technology, Shirpur, Maharashtra', 'Wed Feb 25 2026', 'Sat Mar 07 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/train-z-converges26-r-c-patel-institute-of-technology-shirpur-maharashtra-1648158', 'India', 'hackathons', 'Unstop', '2026-02-26 23:17:25') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Capture The Flag (CTF)', 'MKSSS''s Cummins College of Engineering for Women (CCOEW), Pune', 'Fri Feb 27 2026', 'Fri Apr 10 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/capture-the-flag-ctf-mkssss-cummins-college-of-engineering-for-women-ccoew-pune-1649076', 'India', 'hackathons', 'Unstop', '2026-02-27 03:28:49') ON CONFLICT DO NOTHING;
INSERT INTO events (title, organizer, date, enddate, description, link, location, type, source, createdat) VALUES ('Software Hackathon', 'MKSSS''s Cummins College of Engineering for Women (CCOEW), Pune', 'Fri Feb 27 2026', 'Sat Apr 11 2026', 'Competition hosted on Unstop.', 'https://unstop.com/hackathons/software-hackathon-mkssss-cummins-college-of-engineering-for-women-ccoew-pune-1647418', 'India', 'hackathons', 'Unstop', '2026-02-27 03:28:49') ON CONFLICT DO NOTHING;


COMMIT;
